language: csharp
dist: bionic
mono: none
dotnet: 3.1.302
script:
  - dotnet restore
  - dotnet build
  - dotnet watch test -l "console;verbosity=detailed" david.hotelbooking.UnitTests/david.hotelbooking.UnitTests.csproj
