language: csharp
dist: bionic
mono: none
dotnet: 3.1.302

before_install:
- openssl aes-256-cbc -K $encrypted_bc678f3600cd_key -iv $encrypted_bc678f3600cd_iv
  -in appsettings.json.enc -out appsettings.json -d

script:
- dotnet restore
- dotnet build
- dotnet test -l "console;verbosity=detailed" david.hotelbooking.UnitTests/david.hotelbooking.UnitTests.csproj
