
language: csharp
solution: hotelbooking.sln

jobs:
  include:
      - dotnet: 3.1
        mono: none
        env: DOTNETCORE=3.1
      - mono: latest

install:
  - nuget restore hotelbooking.sln
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - dotnet restore
  - msbuild /p:Configuration=Release hotelbooking.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./david.hotelbooking.UnitTests/bin/Release/MyProject.Tests.dll
  - dotnet test david.hotelbooking.UnitTests/david.hotelbooking.UnitTests.csproj
before_deploy: "echo 'ready?'"
deploy:
  provider: azure_web_apps
  on: feature-mvc
  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
  verbose: true

