language: csharp
dist: bionic
mono: none
dotnet: 3.1.302
env:
  - string=TRAVIS_STRING
script:
  - cat david.hotelbooking.UnitTests/appsettings.json
  - echo string >david.hotelbooking.UnitTests/appsettings.json
  - cat david.hotelbooking.UnitTests/appsettings.json
  - dotnet restore
  - dotnet build
  - dotnet test -l "console;verbosity=detailed" david.hotelbooking.UnitTests/david.hotelbooking.UnitTests.csproj
