# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - davidwuhotelbookingapitests

on:
  push:
    branches:
      - feature-apitests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'
        
    - name: Replace connectionstring in .json
      env: 
        SUPER_SECRET: ${{ secrets.SuperSecret }}
      run: echo "$SUPER_SECRET" >appsettings.json &&
        echo "$SUPER_SECRET" >../david.hotelbooking.mvc/appsettings.json &&
        echo "$SUPER_SECRET" >../david.hotelbooking.UnitTests/appsettings.json 
      working-directory: david.hotelbooking.api 

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet Test
      run: dotnet test -l "console;verbosity=detailed"
      working-directory: david.hotelbooking.AzureApiTests
      

    
